async def seed_doctors(db):
    doctors = [
        {"name": "Dr. Devi Prasad Shetty", "specialization": "Cardiologist (Heart Specialist)", "designation": "Senior Cardiac Surgeon & Chairman", "hospital": "Narayana Health City", "location": "Bangalore, Karnataka", "available_time": "Mon-Sat: 9:00 AM - 1:00 PM", "booking_url": "https://www.narayanahealth.org/book-appointment"},
        {"name": "Dr. Ramakanta Panda", "specialization": "Cardiologist (Heart Specialist)", "designation": "Vice Chairman & MD - Cardiac Surgery", "hospital": "Asian Heart Institute", "location": "Mumbai, Maharashtra", "available_time": "Mon-Fri: 10:00 AM - 2:00 PM", "booking_url": "https://www.asianheartinstitute.org/appointment"},
        {"name": "Dr. T.S. Kler", "specialization": "Cardiologist (Heart Specialist)", "designation": "Chairman - Heart & Vascular Institute", "hospital": "Fortis Escorts Heart Institute", "location": "New Delhi", "available_time": "Tue-Sat: 9:00 AM - 12:00 PM", "booking_url": "https://www.fortishealthcare.com/book-appointment"},
        {"name": "Dr. Naresh Trehan", "specialization": "General Physician (Full Body Checkup)", "designation": "Chairman & Managing Director", "hospital": "Medanta - The Medicity", "location": "Gurugram, Haryana", "available_time": "Mon-Fri: 8:00 AM - 12:00 PM", "booking_url": "https://www.medanta.org/book-an-appointment"},
        {"name": "Dr. Randeep Guleria", "specialization": "General Physician (Full Body Checkup)", "designation": "Director, Institute of Internal Medicine", "hospital": "Apollo Hospitals", "location": "New Delhi", "available_time": "Mon-Sat: 10:00 AM - 3:00 PM", "booking_url": "https://www.apollohospitals.com/book-an-appointment"},
        {"name": "Dr. Ambrish Mithal", "specialization": "Internal Medicine Specialist", "designation": "Chairman, Endocrinology & Diabetes", "hospital": "Max Healthcare", "location": "New Delhi", "available_time": "Mon-Fri: 9:00 AM - 1:00 PM", "booking_url": "https://www.maxhealthcare.in/book-appointment"},
        {"name": "Dr. Suresh Sankhla", "specialization": "Neurologist (Brain and Nervous System Specialist)", "designation": "HOD & Senior Consultant Neurosurgery", "hospital": "Apollo Hospitals", "location": "Mumbai, Maharashtra", "available_time": "Mon-Sat: 10:00 AM - 1:00 PM", "booking_url": "https://www.apollohospitals.com/book-an-appointment"},
        {"name": "Dr. V. Mohan", "specialization": "Endocrinologist (Hormones and Metabolism Specialist)", "designation": "Chairman & Chief Diabetologist", "hospital": "Dr. Mohan's Diabetes Specialities Centre", "location": "Chennai, Tamil Nadu", "available_time": "Mon-Sat: 8:00 AM - 11:00 AM", "booking_url": "https://www.drmohansdiabetes.com/appointment"},
        {"name": "Dr. Arvind Kumar", "specialization": "Pulmonologist (Lung and Breathing Specialist)", "designation": "Chairman, Centre for Chest Surgery", "hospital": "Sir Ganga Ram Hospital", "location": "New Delhi", "available_time": "Mon-Fri: 9:00 AM - 1:00 PM", "booking_url": "https://www.sgrh.com/appointment"},
        {"name": "Dr. D. Nageshwar Reddy", "specialization": "Gastroenterologist (Digestive System Specialist)", "designation": "Chairman & Chief Gastroenterologist", "hospital": "Asian Institute of Gastroenterology", "location": "Hyderabad, Telangana", "available_time": "Mon-Sat: 9:00 AM - 12:00 PM", "booking_url": "https://www.aigindia.com/book-appointment"},
        {"name": "Dr. Sanjeev Gulati", "specialization": "Nephrologist (Kidney Specialist)", "designation": "Principal Director, Nephrology", "hospital": "Fortis Healthcare", "location": "New Delhi", "available_time": "Mon-Sat: 10:00 AM - 2:00 PM", "booking_url": "https://www.fortishealthcare.com/book-appointment"},
        {"name": "Dr. Apratim Goel", "specialization": "Dermatologist (Skin Specialist)", "designation": "Director & Dermatologist", "hospital": "Cutis Skin Studio", "location": "Mumbai, Maharashtra", "available_time": "Mon-Sat: 10:00 AM - 6:00 PM", "booking_url": "https://cutisskin.com/appointment"},
        {"name": "Dr. Ashok Rajgopal", "specialization": "Orthopedic Specialist (Bones, Joints, and Muscles)", "designation": "Chairman, Institute of Musculoskeletal Disorders", "hospital": "Medanta The Medicity", "location": "Gurugram, Haryana", "available_time": "Mon-Fri: 10:00 AM - 1:00 PM", "booking_url": "https://www.medanta.org/book-an-appointment"},
        {"name": "Dr. Mahipal S. Sachdev", "specialization": "Ophthalmologist (Eye Specialist)", "designation": "Chairman, Centre for Sight", "hospital": "Centre for Sight", "location": "New Delhi", "available_time": "Mon-Sat: 9:00 AM - 5:00 PM", "booking_url": "https://www.centreforsight.net/book-appointment"},
        {"name": "Dr. Milind V Kirtane", "specialization": "ENT Specialist (Ear, Nose, and Throat Specialist)", "designation": "Head of ENT Department", "hospital": "Hinduja Hospital", "location": "Mumbai, Maharashtra", "available_time": "Mon-Fri: 10:00 AM - 1:00 PM", "booking_url": "https://hindujahospital.com/appointment"},
        {"name": "Dr. Harish Shetty", "specialization": "Psychiatrist (Mental Health Specialist)", "designation": "Senior Psychiatrist", "hospital": "Dr. L H Hiranandani Hospital", "location": "Mumbai, Maharashtra", "available_time": "Mon-Sat: 10:00 AM - 2:00 PM", "booking_url": "https://hiranandanihospital.org/appointment"},
        {"name": "Dr. Samir Parikh", "specialization": "Psychiatrist (Mental Health Specialist)", "designation": "Director, Department of Mental Health", "hospital": "Fortis Healthcare", "location": "New Delhi", "available_time": "Mon-Fri: 10:00 AM - 1:00 PM", "booking_url": "https://www.fortishealthcare.com/book-appointment"},
        {"name": "Dr. Pradeep Chowbey", "specialization": "General Surgeon (Full Body Surgical Specialist)", "designation": "Chairman, Minimal Access Surgery", "hospital": "Max Super Speciality Hospital", "location": "New Delhi", "available_time": "Mon-Sat: 9:00 AM - 11:00 AM", "booking_url": "https://www.maxhealthcare.in/book-appointment"},
        {"name": "Dr. K.K. Aggarwal", "specialization": "Preventive Medicine Specialist", "designation": "Senior Preventive Medicine Specialist", "hospital": "Moolchand Medcity", "location": "New Delhi", "available_time": "Mon-Fri: 9:00 AM - 5:00 PM", "booking_url": "https://www.moolchandhealthcare.com/appointment"},
        {"name": "Dr. Ashok Seth", "specialization": "Internal Medicine Specialist", "designation": "Chairman, Cardiology", "hospital": "Fortis Escorts Heart Institute", "location": "New Delhi", "available_time": "Tue-Thu: 11:00 AM - 2:00 PM", "booking_url": "https://www.fortishealthcare.com/book-appointment"},
    ]
    await db.doctors.insert_many(doctors)
    print(f"✅ Seeded {len(doctors)} doctors")
